version: '3'
services:

  docker-cache:
    image: rpardini/docker-registry-proxy:${REGISTRY_PROXY_IMAGE_VERSION:-0.6.4}
    container_name: docker-registry-proxy
    # https://docs.docker.com/compose/compose-file/#restart
    restart: unless-stopped
    env_file: # Contains REGISTRIES and AUTH_REGISTRIES
      - ./registries.env
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /opt/docker-data/docker-registry-proxy/docker_mirror_cache:/docker_mirror_cache
      - /opt/docker-data/docker-registry-proxy/ca:/ca
    ports:
      - 0.0.0.0:3128:3128
