version: "3"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This makes IPv6 easier; see below
    restart: unless-stopped
    cap_add:
        # Capability to change user ID; needed for using PUID
      - SETUID
        # Capability to change group ID; needed for using PGID
      - SETGID
    cap_drop:
      # Drop all other capabilities
      - all
    # Make the container filesystem read-only
    read_only: true
    security_opt:
        # Another protection to restrict superuser privileges
      - no-new-privileges:true
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - DOMAINS=${DOMAINS}
      - PROXIED=${PROXIED}
      - IP6_PROVIDER=${IP6_PROVIDER}
      - UPDATE_CRON=${UPDATE_CRON}
