version: '3.8'
services:

  # wireguard:
  #   image: linuxserver/wireguard:latest
  #   container_name: wireguard
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Kaliningrad
  #     - SERVERURL=wireguard.domain.com #optional
  #     - SERVERPORT=51820 #optional
  #     - PEERS=1 #optional
  #     - PEERDNS=auto #optional
  #     - INTERNAL_SUBNET=10.13.13.0 #optional
  #     - ALLOWEDIPS=0.0.0.0/0 #optional
  #     - LOG_CONFS=true #optional
  #   volumes:
  #     - /opt/docker-data/wireguard-server/config:/config
  #     - /lib/modules:/lib/modules
  #   ports:
  #     - 51820:51820/udp
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    # https://docs.docker.com/compose/compose-file/#restart
    restart: ${WGUI_RESTART_POLICY:-unless-stopped}
    # depends_on:
    #   - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: host
    # ports:
    #   - 80:5000
    environment:
      - SESSION_SECRET=${SESSION_SECRET:-Mmi7poKrHwUV7JR4cr4k}
      - WGUI_USERNAME=${WGUI_USERNAME:-test}
      - WGUI_PASSWORD=${WGUI_PASSWORD:-MgRnog7EcRtmq9VvrLHt}
      - WGUI_ENDPOINT_ADDRESS=${WGUI_ENDPOINT_ADDRESS:-}
      - WGUI_SERVER_LISTEN_PORT=${WGUI_SERVER_LISTEN_PORT:-51820}
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /opt/docker-data/wireguard-server/ui-db:/app/db
      # - /opt/docker-data/wireguard-server/config:/etc/wireguard
      - /etc/wireguard:/etc/wireguard
